apiVersion: v1
kind: ServiceAccount
metadata:
  name: mindwell-backend
  labels:
    app: mindwell-backend
  annotations:
    azure.workload.identity/client-id: ${AKS_MANAGED_IDENTITY_CLIENT_ID}
    azure.workload.identity/use: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindwell-backend
  labels:
    app: mindwell-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mindwell-backend
  template:
    metadata:
      labels:
        app: mindwell-backend
    spec:
      serviceAccountName: mindwell-backend
      containers:
        - name: api
          image: ${BACKEND_IMAGE}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - secretRef:
                name: mindwell-backend
          volumeMounts:
            - name: backend-secrets
              mountPath: /mnt/secrets
              readOnly: true
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: backend-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: backend-secrets
