apiVersion: v1
kind: Service
metadata:
  name: mindwell-backend
  labels:
    app: mindwell-backend
spec:
  type: ClusterIP
  selector:
    app: mindwell-backend
  ports:
    - name: http
      port: 80
      targetPort: http
