name: MindWell Release Bundles

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (e.g. staging, prod)"
        required: false
        default: "staging"

jobs:
  backend-package:
    name: Backend Wheel
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: services/backend/pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev] build

      - name: Run unit tests
        run: pytest -q

      - name: Build distribution artifacts
        run: python -m build

      - name: Upload backend artefacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: |
            services/backend/dist/*.whl
            services/backend/dist/*.tar.gz

  web-build:
    name: Web Production Build
    runs-on: ubuntu-latest
    needs: backend-package

    defaults:
      run:
        working-directory: clients/web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: clients/web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test -- --run

      - name: Build web bundle
        run: npm run build

      - name: Package dist artefacts
        run: tar -czf web-dist.tar.gz -C dist .

      - name: Upload web artefact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: clients/web/web-dist.tar.gz

  mobile-bundle:
    name: Mobile Release Bundles
    runs-on: ubuntu-latest
    needs: backend-package

    defaults:
      run:
        working-directory: clients/mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: clients/mobile/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build release bundles
        run: npm run build:release

      - name: Package export artefacts
        run: tar -czf mobile-release.tar.gz -C build/release .

      - name: Upload mobile artefact
        uses: actions/upload-artifact@v4
        with:
          name: mobile-release
          path: clients/mobile/mobile-release.tar.gz

  summary:
    name: Release Summary
    runs-on: ubuntu-latest
    needs:
      - backend-package
      - web-build
      - mobile-bundle
    steps:
      - name: Release artefacts available
        run: |
          echo "Backend wheel, web dist bundle, and mobile export uploaded as workflow artefacts."
